[package]
name = "abstutil"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[features]
profiler = ["cpuprofiler"]

[dependencies]
bincode = "1.1.2"
cpuprofiler = { version = "0.0.3", optional = true }
instant = "0.1.2"
itertools = "0.9.0"
lazy_static = "1.4.0"
log = { version = "0.4", features=["std"] }
num_cpus = "1.10.0"
rand = "0.7.0"
rand_xorshift = "0.2.0"
scoped_threadpool = "0.1.9"
serde = "1.0.110"
serde_json = "1.0.40"

[target.'cfg(unix)'.dependencies]
termion = "1.5.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
include_dir = "0.5.0"
